
###########################################################################
#             This file is generated by RCH/CapistranoBundle              #
#                                                                         #
#               https://github.com/chalasr/CapistranoBundle               #
#                  Robin Chalas <robin.chalas@gmail.com>                  #
#                                                                         #
###########################################################################


gem 'capistrano'
gem 'capistrano-symfony'
gem 'capistrano-rbenv'