###########################################################################
#          This file is generated by Chalasdev/CapistranoBundle           #
#                                                                         #
#               https://github.com/chalasr/CapistranoBundle               #
#                  Robin Chalas <robin.chalas@gmail.com>                  #
#                                                                         #
###########################################################################

# Default
set :app_path, 'app'
set :web_path, 'web'
set :scm, 'git'
set :format, :pretty
set :log_level, :debug
set :stage, "production"
set :pty, true
set :log_path, fetch(:app_path) + "/logs"
set :cache_path, fetch(:app_path) + "/cache"
set :app_config_path, fetch(:app_path) + "/config"
set :linked_dirs, %w{app/logs}
# set :linked_files, ["app/config/parameters.yml"]

# Permissions
set :file_permissions_paths, [fetch(:log_path), fetch(:cache_path)]
set :file_permissions_users, ['www-data']
set :webserver_user, "www-data"

# Assets
set :assets_install_path, fetch(:web_path)
set :assets_install_flags, '--symlink'

# Server
set :application, 'sportroops'
set :repo_url, 'git@git.sutunam.com:sluaire/sportroops-com.git'
set :branch, 'dev'
set :ssh_user, 'sportroops.dev5.sutunam.com'
set :deploy_to, '/home/sportroops.dev5.sutunam.com/public_html'
set :model_manager, 'doctrine'
set :symfony_env, 'prod'
set :use_sudo, false
set :use_set_permissions, true
set :permission_method, :chmod
set :keep_releases, 3

namespace :composer do
    before 'install', 'download'
    desc 'Composer update'
    task :download do
        on roles(:all) do
            execute "cd #{deploy_to} && curl -s https://getcomposer.org/installer | php"
        end
    end
end
SSHKit.config.command_map[:composer] = "php #{deploy_to}/composer.phar"
set :composer_install_flags, '--no-dev --quiet --no-interaction --optimize-autoloader'
set :composer_dump_autoload_flags, '--optimize'

namespace :deploy do
  before 'updated', 'schemadb'
  task :schemadb do
    invoke 'symfony:console', 'doctrine:schema:update', '--force'
  end
end
