###########################################################################
#          This file is generated by Chalasdev/CapistranoBundle           #
#                                                                         #
#               https://github.com/chalasr/CapistranoBundle               #
#                  Robin Chalas <robin.chalas@gmail.com>                  #
#                                                                         #
###########################################################################

server 'sportroops.dev5.sutunam.com',
user: 'sportroops.dev5.sutunam.com',
ssh_options: {
		user: 'sportroops.dev5.sutunam.com',
		keys: %w(/home/sportroops.dev5.sutunam.com/.ssh/id_rsa),
		forward_agent: true,
		auth_methods: %w(publickey password),
}